### ISSUE TITLE
Test failure on 0.5.0 (due to pickling failure)

### ISSUE THREAD

**Issue by jakirkham** [lucastheis/cmt#12]
Here is the failures that we are seeing. Using Python 2.7.11, NumPy 1.10.4, and gcc 4.8.5.

```
python /zopt/conda2/conda-bld/work/cmt-0.5.0/code/cmt/python/tests/mcbm_test.py
.....E....
======================================================================
ERROR: test_patchmcbm_pickle (__main__.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/zopt/conda2/conda-bld/work/cmt-0.5.0/code/cmt/python/tests/mcbm_test.py", line 364, in test_patchmcbm_pickle
    dump({'model': model0}, handle)
  File "/zopt/conda2/envs/_test/lib/python2.7/pickle.py", line 1376, in dump
    Pickler(file, protocol).dump(obj)
  File "/zopt/conda2/envs/_test/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/zopt/conda2/envs/_test/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/zopt/conda2/envs/_test/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/zopt/conda2/envs/_test/lib/python2.7/pickle.py", line 669, in _batch_setitems
    save(v)
  File "/zopt/conda2/envs/_test/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/zopt/conda2/envs/_test/lib/python2.7/pickle.py", line 425, in save_reduce
    save(state)
  File "/zopt/conda2/envs/_test/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/zopt/conda2/envs/_test/lib/python2.7/pickle.py", line 568, in save_tuple
    save(element)
  File "/zopt/conda2/envs/_test/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/zopt/conda2/envs/_test/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/zopt/conda2/envs/_test/lib/python2.7/pickle.py", line 669, in _batch_setitems
    save(v)
  File "/zopt/conda2/envs/_test/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/zopt/conda2/envs/_test/lib/python2.7/pickle.py", line 400, in save_reduce
    save(func)
  File "/zopt/conda2/envs/_test/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/zopt/conda2/envs/_test/lib/python2.7/pickle.py", line 754, in save_global
    (obj, module, name))
PicklingError: Can't pickle <type 'cmt.transforms.PCATransform'>: it's not found as cmt.transforms.PCATransform

----------------------------------------------------------------------
Ran 10 tests in 0.401s

FAILED (errors=1)
```

**Comment by FlorianFranzen** [comment]
Is this fixed in the latest release [v0.6.0](https://github.com/lucastheis/cmt/releases/tag/v0.6.0)?

**Comment by jakirkham** [comment]
I'm not sure. I did build the latest version, but need to retest if this is fixed. It may be.
