### ISSUE TITLE
Test failure on 0.5.0 (due to missing import)

### ISSUE THREAD

**Issue by jakirkham** [lucastheis/cmt#14]
Looks like there is a missing import in 0.5.0 and `master`. This is due to Pillow being required and the import being incorrect [here](https://github.com/lucastheis/cmt/blob/master/code/cmt/python/tools/images.py#L1). Guessing this is suppose to be `from PIL import Image`. Though it if is optional, we should be suppressing the `ImportError` that is raised when Pillow is not installed. Here is the error I am seeing.

```
python /zopt/conda2/conda-bld/work/cmt-0.5.0/code/cmt/python/tests/tools_test.py
Traceback (most recent call last):
  File "/zopt/conda2/conda-bld/work/cmt-0.5.0/code/cmt/python/tests/tools_test.py", line 11, in <module>
    from cmt.tools import generate_data_from_image, sample_image
  File "/zopt/conda2/envs/_test/lib/python2.7/site-packages/cmt/tools/__init__.py", line 34, in <module>
    from images import imwrite, imread, imformat
  File "/zopt/conda2/envs/_test/lib/python2.7/site-packages/cmt/tools/images.py", line 1, in <module>
    import Image
ImportError: No module named Image
```

**Comment by jakirkham** [comment]
Resolved in 0.6.0.
